name: 'Qt Mingw64 Static'

on:
  push:
    branches:
      - mingw64
jobs:
  win64-msvc:
    name: Qt Mingw64 Static
    runs-on: windows-2019
    env:
      INSTALL_PREFIX: 'C:\QtStaticMingw64'
      OS: "win64-msvc"
      QT_VERSION: "v6.4.0"
    steps:
      - name: Set Mingw64
        run: |
          (new-object System.Net.WebClient).DownloadFile('https://github.com/brechtsanders/winlibs_mingw/releases/download/12.2.0-14.0.6-10.0.0-ucrt-r2/winlibs-x86_64-posix-seh-gcc-12.2.0-mingw-w64ucrt-10.0.0-r2.7z','mingw64.7z')
          7z x -aoa -oC:\ mingw64.7z
          del mingw64.7z
      - name: Build script
        run: |
          $env:Path = "C:\mingw64\bin;$env:Path"
          cd C:/
          git clone https://code.qt.io/qt/qt5.git -b 6.4.0
          cd qt5
          perl init-repository -f --module-subset=default
          ./configure.bat -release -static -static-runtime -platform win32-g++ -prefix "C:\QtStaticMingw64" -confirm-license -nomake examples -nomake tests
          cmake --build . --parallel 4
          cmake --install .
      - uses: actions/upload-artifact@v3
        with:
          name: qt6_mingw64_static.zip
          path: C:\QtStaticMingw64
