name: 'mingw64-official-script Action'

on:
  push:
    branches:
      - mingw64-official-script
jobs:
  mingw64-win:
    name: mingw64 Action
    runs-on: windows-2019
    env:
      INSTALL_PREFIX: 'C:\QtStaticMingw64'
      OS: "win64-msvc"
      QT_VERSION: "v6.4.0"
    steps:
      - name: Set Mingw64
        run: |
          (new-object System.Net.WebClient).DownloadFile('https://github.com/cristianadam/mingw-builds/releases/download/v11.2.0-rev3/x86_64-11.2.0-release-posix-seh-rt_v9-rev3.7z','mingw64.7z')
          7z x -aoa -oC:\ mingw64.7z
          del mingw64.7z
      - name: Build script
        run: |
          $Env:PATH = "C:\mingw64\bin;$Env:PATH"
          gcc -v
          cd C:/
          git clone --depth=1 https://github.com/axojhf/qt-build.git -b mingw64-official-script
          cd qt-build
          ./qt-windows-static-build.ps1
      - uses: actions/upload-artifact@v3
        with:
          name: qt6_mingw_static
          path: C:/QtStaticMingw64
