name: 'Qt Creator Build'

on:
  push:
    branches:
      - qt-creator
jobs:
  qt650:
    name: Qt Creator master MinGW64 Build
    runs-on: windows-2019
    steps:
      - name: Set Mingw64 Ninja
        run: |
          (new-object System.Net.WebClient).DownloadFile('https://github.com/cristianadam/mingw-builds/releases/download/v11.2.0-rev3/x86_64-11.2.0-release-posix-seh-rt_v9-rev3.7z','mingw64.7z')
          7z x -aoa -oC:\ mingw64.7z ; rm mingw64.7z
          (new-object System.Net.WebClient).DownloadFile('https://github.com/ninja-build/ninja/releases/download/v1.11.1/ninja-win.zip','ninja-win.zip')
          7z x -aoa -oC:\ninja ninja-win.zip ; rm ninja-win.zip
      - name: Install Qt
        uses: jurplel/install-qt-action@v3
        with:
          dir: 'C:/'
          aqtversion: '==3.1.*'
          py7zrversion: '>=0.20.2'
          version: '6.5.0'
          host: 'windows'
          target: 'desktop'
          arch: 'win64_mingw'
          modules: 'qt3d qtactiveqt qtcharts qtconnectivity qtdatavis3d qtgrpc qthttpserver qtimageformats qtlanguageserver qtlocation qtlottie qtmultimedia qtnetworkauth qtpositioning qtquick3dphysics qtquickeffectmaker qtremoteobjects qtscxml qtsensors qtserialbus qtserialport qtspeech qtvirtualkeyboard qtwebchannel qtwebsockets qtwebview debug_info qt5compat qtquick3d qtquicktimeline qtshadertools'
      - name: Build
        run: |
          # ls C:\Qt\6.5.0\mingw_64\bin
          # $env:Path = "C:\mingw64\bin;C:\ninja;C:\Qt\6.5.0\mingw_64\bin;C:\Qt\6.5.0\mingw_64$env:Path"
          $qtpath1 = Get-ChildItem -Path 'C:\Qt' | Select-Object -First 1
          $qtpath2 = Get-ChildItem -Path $qtpath1.FullName | Select-Object -First 1
          $qtpathFullName = $qtpath2.FullName
          Write-Output $qtpathFullName
          $env:Path = "C:\mingw64\bin;C:\ninja;$qtpathFullName\bin;$qtpathFullName;$env:Path"
          cd C:\
          git clone --depth=1 https://code.qt.io/qt-creator/qt-creator.git
          cd qt-creator ; git submodule update --init --recursive
          mkdir build ; cd build
          cmake .. -DCMAKE_BUILD_TYPE=Release -GNinja -DCMAKE_PREFIX_PATH=C:\qt-creator-install
          cmake --build . ; cmake --install . --prefix C:\qt-creator-install
      - name: Package Directories
        run: |
          7z a qt-creator-mingw64-latest.7z C:\qt-creator-install
      - name: Update QtCreator Master MinGW64 Release
        uses: softprops/action-gh-release@v1
        with:
          tag_name: qt-creator-master
          files: |
            qt-creator-mingw64-latest.7z

  qt650-msvc:
    name: Qt Creator master MSVC2022 Build
    runs-on: windows-2022
    steps:
      - name: Set Mingw64 Ninja
        run: |
          # (new-object System.Net.WebClient).DownloadFile('https://github.com/cristianadam/mingw-builds/releases/download/v11.2.0-rev3/x86_64-11.2.0-release-posix-seh-rt_v9-rev3.7z','mingw64.7z')
          # 7z x -aoa -oC:\ mingw64.7z ; rm mingw64.7z
          (new-object System.Net.WebClient).DownloadFile('https://github.com/ninja-build/ninja/releases/download/v1.11.1/ninja-win.zip','ninja-win.zip')
          7z x -aoa -oC:\ninja ninja-win.zip ; rm ninja-win.zip
      - name: Install Qt
        uses: jurplel/install-qt-action@v3
        with:
          dir: 'C:/'
          aqtversion: '==3.1.*'
          py7zrversion: '>=0.20.2'
          version: '6.5.0'
          host: 'windows'
          target: 'desktop'
          arch: 'win64_msvc2019_64'
          modules: 'qt3d qtactiveqt qtcharts qtconnectivity qtdatavis3d qtgrpc qthttpserver qtimageformats qtlanguageserver qtlocation qtlottie qtmultimedia qtnetworkauth qtpdf qtpositioning qtquick3dphysics qtquickeffectmaker qtremoteobjects qtscxml qtsensors qtserialbus qtserialport qtspeech qtvirtualkeyboard qtwebchannel qtwebengine qtwebsockets qtwebview debug_info qt5compat qtquick3d qtquicktimeline qtshadertools'
      - uses: ilammy/msvc-dev-cmd@v1
        with:
          arch: amd64
          toolset: 14.3
      - name: Build
        run: |
          $qtpath1 = Get-ChildItem -Path 'C:\Qt' | Select-Object -First 1
          $qtpath2 = Get-ChildItem -Path $qtpath1.FullName | Select-Object -First 1
          $qtpathFullName = $qtpath2.FullName
          Write-Output $qtpathFullName
          $env:Path = "C:\ninja;$qtpathFullName\bin;$qtpathFullName;$env:Path"
          cd C:\
          git clone --depth=1 https://code.qt.io/qt-creator/qt-creator.git
          cd qt-creator ; git submodule update --init --recursive
          mkdir build ; cd build
          cmake .. -DCMAKE_BUILD_TYPE=Release -GNinja -DCMAKE_PREFIX_PATH=C:\qt-creator-install
          cmake --build . ; cmake --install . --prefix C:\qt-creator-install
      - name: Package Directories
        run: |
          7z a qt-creator-msvc-latest.7z C:\qt-creator-install
      - name: Update QtCreator Master MSVC Release
        uses: softprops/action-gh-release@v1
        with:
          tag_name: qt-creator-master
          files: |
            qt-creator-msvc-latest.7z

