name: 'test Action'

on:
  push:
    branches:
      - test
jobs:
  mingw64-win:
    name: mingw64 Action
    runs-on: windows-2019
    env:
      INSTALL_PREFIX: 'C:\QtStaticMingw64'
      OS: "win64-msvc"
      QT_VERSION: "v6.4.0"
    steps:
      - name: Set Mingw64
        run: |
          (new-object System.Net.WebClient).DownloadFile('https://github.com/brechtsanders/winlibs_mingw/releases/download/12.2.0-14.0.6-10.0.0-ucrt-r2/winlibs-x86_64-posix-seh-gcc-12.2.0-mingw-w64ucrt-10.0.0-r2.7z','mingw64.7z')
          7z x -aoa -oC:\mingw64 mingw64.7z 
          del mingw64.7z
          cd C:\mingw64\bin
      - name: Build script
        run: |
          $Env:PATH = C:\mingw64\bin;$Env:PATH
          gcc -v
      - uses: actions/upload-artifact@v3
        with:
          name: qt6_mingw_static
          path: C:/QtStaticMingw64
