name: 'vstools Build'

on:
  push:
    branches:
      - vstools
jobs:
  try:
    name: vstools Build
    runs-on: windows-2022
    steps:
      - name: Install Qt
        uses: jurplel/install-qt-action@v3
        with:
          dir: 'C:\'
          aqtversion: '==3.1.*'
          py7zrversion: '>=0.20.2'
          version: '5.12.9'
          host: 'windows'
          target: 'desktop'
          arch: 'win64_msvc2017_64'
      - uses: ilammy/msvc-dev-cmd@v1
        with:
          arch: amd64
          toolset: 14.3
      - name: Build script
        run: |
          $qtpath1 = Get-ChildItem -Path 'C:\Qt' | Select-Object -First 1
          $qtpath2 = Get-ChildItem -Path $qtpath1.FullName | Select-Object -First 1
          $qtpathFullName = $qtpath2.FullName
          Write-Output $qtpathFullName
          $env:QTBUILD_STATIC_VS2022 = "$qtpathFullName"
          cd C:\ ; git clone https://github.com/qt-labs/vstools.git ; cd vstools
          .\vstools.bat -init
          .\vstools.bat -vs2022 -build -deploy C:\vstools_install
      - name: Package binaries
        run: |
          7z a qt_vstools_latest_dynamic.7z C:\vstools_install
      - name: Update Static Qt Dev MSVC Release
        uses: softprops/action-gh-release@v1
        with:
          tag_name: qt-vstools-build
          files: |
            qt_vstools_latest_dynamic.7z

  qt515:
    name: vstools Build Qt 5.15
    runs-on: windows-2022
    steps:
      - name: Install LLVM
        run: |
          (new-object System.Net.WebClient).DownloadFile('https://github.com/ninja-build/ninja/releases/download/v1.11.1/ninja-win.zip','ninja-win.zip')
          7z x -aoa -oC:\ninja ninja-win.zip ; rm ninja-win.zip
          # (new-object System.Net.WebClient).DownloadFile('https://github.com/BtbN/FFmpeg-Builds/releases/download/latest/ffmpeg-master-latest-win64-gpl-shared.zip','ffmpeg-master-latest-win64-gpl-shared.zip')
          # 7z x -aoa -oC:\ ffmpeg-master-latest-win64-gpl-shared.zip ; ren C:\ffmpeg-master-latest-win64-gpl-shared ffmpeg ; rm ffmpeg-master-latest-win64-gpl-shared.zip
          # (new-object System.Net.WebClient).DownloadFile('https://download.firedaemon.com/FireDaemon-OpenSSL/openssl-1.1.1t.zip','openssl.zip')
          # 7z x -aoa -oC:\ openssl.zip ; rm openssl.zip
      - uses: ilammy/msvc-dev-cmd@v1
        with:
          arch: amd64
          toolset: 14.3
      - name: Build script
        run: |
          $Env:PATH = "C:\ninja;$Env:PATH"
          cd C:/ ; git clone --depth=1 https://code.qt.io/qt/qt5.git -b 5.12.10 ; cd qt5
          perl init-repository -f --module-subset=qtbase,qtdeclarative
          ./configure.bat -release -static -platform win32-msvc -prefix "C:\Qt5.12" -confirm-license -nomake examples -nomake tests -qt-zlib -qt-libjpeg -qt-libpng -qt-freetype -qt-pcre -qt-harfbuzz -qt-sqlite -no-sql-psql -no-sql-mysql
          nmake
          nmake install
          $env:QTBUILD_STATIC_VS2022 = "C:\Qt5.12"
          cd C:\ ; git clone https://github.com/qt-labs/vstools.git ; cd vstools
          .\vstools.bat -init
          .\vstools.bat -vs2022 -build -deploy C:\vstools_install
      - name: Package binaries
        run: |
          7z a qt_vstools_latest.7z C:\vstools_install
      - name: Update Static Qt Dev MSVC Release
        uses: softprops/action-gh-release@v1
        with:
          tag_name: qt-vstools-build
          files: |
            qt_vstools_latest.7z