name: 'Qt Mingw64 Static'

on:
  push:
    branches:
      - mingw64
jobs:
  # win64-msvc:
  #   name: Qt Mingw64 Static
  #   runs-on: windows-2019
  #   env:
  #     INSTALL_PREFIX: 'C:\QtStaticMingw64'
  #     OS: "win64-msvc"
  #     QT_VERSION: "v6.4.0"
  #   steps:
  #     - name: Set Mingw64
  #       run: |
  #         (new-object System.Net.WebClient).DownloadFile('https://github.com/cristianadam/mingw-builds/releases/download/v11.2.0-rev3/x86_64-11.2.0-release-posix-seh-rt_v9-rev3.7z','mingw64.7z')
  #         7z x -aoa -oC:\ mingw64.7z
  #         del mingw64.7z
  #     - name: Build script
  #       run: |
  #         $env:Path = "C:\mingw64\bin;$env:Path"
  #         cd C:/
  #         git clone https://code.qt.io/qt/qt5.git -b 6.4.0
  #         cd qt5
  #         perl init-repository -f --module-subset=default
  #         ./configure.bat -release -static -static-runtime -platform win32-g++ -prefix "C:\QtStaticMingw64" -confirm-license -nomake examples -nomake tests
  #         cmake --build . --parallel 4
  #         cmake --install .
  #     - uses: actions/upload-artifact@v3
  #       with:
  #         name: qt6_mingw64_static.zip
  #         path: C:\QtStaticMingw64
  mingw64-mini-for-gui:
    name: Qt Mingw64 Static
    runs-on: windows-2019
    env:
      INSTALL_PREFIX: 'C:\QtStaticMingw64'
      OS: "win32-g++"
      QT_VERSION: "v6.4.0"
    steps:
      # - name: Del VCPKG
      #   run: |
      #     rm C:/vcpkg -r -force
      - name: Set Mingw64 Ninja
        run: |
          (new-object System.Net.WebClient).DownloadFile('https://github.com/cristianadam/mingw-builds/releases/download/v11.2.0-rev3/x86_64-11.2.0-release-posix-seh-rt_v9-rev3.7z','mingw64.7z')
          7z x -aoa -oC:\ mingw64.7z
          del mingw64.7z
          (new-object System.Net.WebClient).DownloadFile('https://github.com/ninja-build/ninja/releases/download/v1.11.1/ninja-win.zip','ninja-win.zip')
          7z x -aoa -oC:\ninja ninja-win.zip
          del ninja-win.zip
      # - uses: ilammy/msvc-dev-cmd@v1
      #   with:
      #     arch: amd64
      #     toolset: 14.2
      - name: Build script
        run: |
          $env:Path = "C:\mingw64\bin;C:\ninja;$env:Path"
          cd C:/
          git clone https://code.qt.io/qt/qt5.git -b 6.4.0
          cd qt5
          perl init-repository -f --module-subset=qt5compat,qt3d,qtactiveqt,qtbase,qtcharts,qtdatavis3d,qtdeclarative,qtimageformats,qtmultimedia,qtquick3d,qtquicktimeline,qtshadertools,qtsvg,qtwebsockets,qttools,qttranslations,qtlottie,qtvirtualkeyboard
          ./configure.bat -release -static -platform win32-g++ -prefix "C:\QtStaticMingw64" -confirm-license -nomake examples -nomake tests
          cmake --build . --parallel 4
          cmake --install .
      - name: Package Directories
        run: |
          7z a qt6_static.7z C:\QtStaticMingw64
      - uses: actions/upload-artifact@v3
        with:
          name: qt6_mingw64_static_small_for_gui
          path: qt6_static.7z
