name: 'Static Multiple Build'

on:
  push:
    branches:
      - static
jobs:
  static-mingw64-dev:
    name: Static Qt Dev MinGW64
    runs-on: windows-2019
    steps:
      - name: Set Mingw64 Ninja FFmpeg OpenSSL
        run: |
          (new-object System.Net.WebClient).DownloadFile('https://github.com/cristianadam/mingw-builds/releases/download/v11.2.0-rev3/x86_64-11.2.0-release-posix-seh-rt_v9-rev3.7z','mingw64.7z')
          7z x -aoa -oC:\ mingw64.7z ; rm mingw64.7z
          (new-object System.Net.WebClient).DownloadFile('https://github.com/ninja-build/ninja/releases/download/v1.11.1/ninja-win.zip','ninja-win.zip')
          7z x -aoa -oC:\ninja ninja-win.zip ; rm ninja-win.zip
          (new-object System.Net.WebClient).DownloadFile('https://github.com/BtbN/FFmpeg-Builds/releases/download/latest/ffmpeg-master-latest-win64-gpl-shared.zip','ffmpeg-master-latest-win64-gpl-shared.zip')
          7z x -aoa -oC:\ ffmpeg-master-latest-win64-gpl-shared.zip ; ren C:\ffmpeg-master-latest-win64-gpl-shared ffmpeg ; rm ffmpeg-master-latest-win64-gpl-shared.zip
          # (new-object System.Net.WebClient).DownloadFile('https://download.firedaemon.com/FireDaemon-OpenSSL/openssl-3.1.2.zip','openssl.zip')
          # 7z x -aoa -oC:\ openssl.zip ; rm openssl.zip
      - name: Init Qt Repository
        run: |
          $env:Path = "C:\mingw64\bin;C:\ninja;C:\ffmpeg\include;C:\ffmpeg\lib;C:\ffmpeg\bin;$env:Path"
          cd C:/ ; git clone --depth=1 https://github.com/qt/qt5.git -b dev ; cd qt5
          perl init-repository -f --module-subset=qt5compat,qt3d,qtbase,qtcharts,qtdeclarative,qtimageformats,qtquicktimeline,qtquick3d,qtshadertools,qtsvg,qtmultimedia
      - name: Build
        run: |
          $env:Path = "C:\openssl-3\x64\lib;C:\openssl-3\x64\include;C:\mingw64\bin;C:\ninja;C:\ffmpeg\include;C:\ffmpeg\lib;C:\ffmpeg\bin;C:\Strawberry\perl\bin;C:\hostedtoolcache\windows\Python\3.7.9\x64;C:\Program Files\PowerShell\7;C:\Program Files\CMake\bin;C:\Windows\System32\WindowsPowerShell\v1.0"
          $env:QT_MEDIA_BACKEND = "ffmpeg"
          $env:FFMPEG_INCLUDE_DIRS = "C:\ffmpeg\include"
          $env:FFMPEG_LIBRARY_DIRS = "C:\ffmpeg\lib"
          cd C:/qt5
          ./configure.bat -release -static -platform win32-g++ -prefix "C:\QtDevMinGw64Static" -confirm-license -nomake examples -nomake tests -schannel -qt-zlib -qt-libjpeg -qt-libpng -qt-freetype -qt-pcre -qt-harfbuzz -qt-sqlite -no-sql-psql -no-sql-mysql -qt-tiff -qt-webp
          cmake --build . --parallel 4
          cmake --install .
      - name: Package Directories
        run: |
          7z a qt6_dev_mingw64_static.7z C:\QtDevMinGw64Static
      - name: Update Static Qt Dev MinGW64 Release
        uses: softprops/action-gh-release@v1
        with:
          tag_name: qt-static
          files: |
            qt6_dev_mingw64_static.7z

  static-win32-msvc-dev:
    name: Static Qt Dev MSVC Build
    runs-on: windows-2022
    steps:
      - name: Install LLVM
        run: |
          # (new-object System.Net.WebClient).DownloadFile('https://github.com/llvm/llvm-project/releases/download/llvmorg-16.0.2/LLVM-16.0.2-win64.exe','LLVM-win64.exe')
          # 7z x -aoa -oC:\LLVM LLVM-win64.exe ; rm LLVM-win64.exe
          (new-object System.Net.WebClient).DownloadFile('https://github.com/ninja-build/ninja/releases/download/v1.11.1/ninja-win.zip','ninja-win.zip')
          7z x -aoa -oC:\ninja ninja-win.zip ; rm ninja-win.zip
          (new-object System.Net.WebClient).DownloadFile('https://github.com/BtbN/FFmpeg-Builds/releases/download/latest/ffmpeg-master-latest-win64-gpl-shared.zip','ffmpeg-master-latest-win64-gpl-shared.zip')
          7z x -aoa -oC:\ ffmpeg-master-latest-win64-gpl-shared.zip ; ren C:\ffmpeg-master-latest-win64-gpl-shared ffmpeg ; rm ffmpeg-master-latest-win64-gpl-shared.zip
          # (new-object System.Net.WebClient).DownloadFile('https://download.firedaemon.com/FireDaemon-OpenSSL/openssl-3.1.2.zip','openssl.zip')
          # 7z x -aoa -oC:\ openssl.zip ; rm openssl.zip
      - uses: ilammy/msvc-dev-cmd@v1
        with:
          arch: amd64
          toolset: 14.3
      - name: Build script
        run: |
          $Env:PATH = "C:\ninja;C:\ffmpeg\include;C:\ffmpeg\lib;C:\ffmpeg\bin;C:\openssl-3\x64\lib;C:\openssl-3\x64\include;$Env:PATH"
          cd C:/ ; git clone --depth=1 https://code.qt.io/qt/qt5.git -b dev ; cd qt5
          perl init-repository -f --module-subset=qt5compat,qt3d,qtbase,qtcharts,qtdeclarative,qtimageformats,qtquicktimeline,qtquick3d,qtshadertools,qtsvg,qtmultimedia
          ./configure.bat -release -static -platform win32-msvc -prefix "C:\QtDevMSVCStatic" -confirm-license -nomake examples -nomake tests -schannel -qt-zlib -qt-libjpeg -qt-libpng -qt-freetype -qt-pcre -qt-harfbuzz -qt-sqlite -no-sql-psql -no-sql-mysql -qt-tiff -qt-webp
          cmake --build . --parallel 4
          cmake --install .
      - name: Package binaries
        run: |
          7z a qt6_dev_vc143_static.7z C:\QtDevMSVCStatic
      - name: Update Static Qt Dev MSVC Release
        uses: softprops/action-gh-release@v1
        with:
          tag_name: qt-static
          files: |
            qt6_dev_vc143_static.7z

  static-65-win32-msvc-dev:
    name: Static Qt 6.5 MSVC Build
    runs-on: windows-2022
    steps:
      - name: Install LLVM
        run: |
          (new-object System.Net.WebClient).DownloadFile('https://github.com/ninja-build/ninja/releases/download/v1.11.1/ninja-win.zip','ninja-win.zip')
          7z x -aoa -oC:\ninja ninja-win.zip ; rm ninja-win.zip
          (new-object System.Net.WebClient).DownloadFile('https://github.com/BtbN/FFmpeg-Builds/releases/download/latest/ffmpeg-master-latest-win64-gpl-shared.zip','ffmpeg-master-latest-win64-gpl-shared.zip')
          7z x -aoa -oC:\ ffmpeg-master-latest-win64-gpl-shared.zip ; ren C:\ffmpeg-master-latest-win64-gpl-shared ffmpeg ; rm ffmpeg-master-latest-win64-gpl-shared.zip
          # (new-object System.Net.WebClient).DownloadFile('https://download.firedaemon.com/FireDaemon-OpenSSL/openssl-3.1.2.zip','openssl.zip')
          # 7z x -aoa -oC:\ openssl.zip ; rm openssl.zip
      - uses: ilammy/msvc-dev-cmd@v1
        with:
          arch: amd64
          toolset: 14.3
      - name: Build script
        run: |
          $Env:PATH = "C:\ninja;C:\ffmpeg\include;C:\ffmpeg\lib;C:\ffmpeg\bin;C:\openssl-3\x64\lib;C:\openssl-3\x64\include;$Env:PATH"
          cd C:/ ; git clone --depth=1 https://code.qt.io/qt/qt5.git -b 6.5 ; cd qt5
          perl init-repository -f --module-subset=qt5compat,qt3d,qtbase,qtcharts,qtdeclarative,qtimageformats,qtquicktimeline,qtquick3d,qtshadertools,qtsvg,qtmultimedia
          ./configure.bat -release -static -platform win32-msvc -prefix "C:\QtDevMSVCStatic" -confirm-license -nomake examples -nomake tests -schannel -qt-zlib -qt-libjpeg -qt-libpng -qt-freetype -qt-pcre -qt-harfbuzz -qt-sqlite -no-sql-psql -no-sql-mysql -qt-tiff -qt-webp
          cmake --build . --parallel 4
          cmake --install .
      - name: Package binaries
        run: |
          7z a qt6.5_vc143_static.7z C:\QtDevMSVCStatic
      - name: Update Static Qt 6.5 MSVC Release
        uses: softprops/action-gh-release@v1
        with:
          tag_name: qt-static
          files: |
            qt6.5_vc143_static.7z

  static-66-win32-msvc-dev:
    name: Static Qt 6.6 MSVC Build
    runs-on: windows-2022
    steps:
      - name: Install LLVM
        run: |
          (new-object System.Net.WebClient).DownloadFile('https://github.com/ninja-build/ninja/releases/download/v1.11.1/ninja-win.zip','ninja-win.zip')
          7z x -aoa -oC:\ninja ninja-win.zip ; rm ninja-win.zip
          (new-object System.Net.WebClient).DownloadFile('https://github.com/BtbN/FFmpeg-Builds/releases/download/latest/ffmpeg-master-latest-win64-gpl-shared.zip','ffmpeg-master-latest-win64-gpl-shared.zip')
          7z x -aoa -oC:\ ffmpeg-master-latest-win64-gpl-shared.zip ; ren C:\ffmpeg-master-latest-win64-gpl-shared ffmpeg ; rm ffmpeg-master-latest-win64-gpl-shared.zip
          # (new-object System.Net.WebClient).DownloadFile('https://download.firedaemon.com/FireDaemon-OpenSSL/openssl-3.1.2.zip','openssl.zip')
          # 7z x -aoa -oC:\ openssl.zip ; rm openssl.zip
      - uses: ilammy/msvc-dev-cmd@v1
        with:
          arch: amd64
          toolset: 14.3
      - name: Build script
        run: |
          $Env:PATH = "C:\ninja;C:\ffmpeg\include;C:\ffmpeg\lib;C:\ffmpeg\bin;C:\openssl-3\x64\lib;C:\openssl-3\x64\include;$Env:PATH"
          cd C:/ ; git clone --depth=1 https://code.qt.io/qt/qt5.git -b 6.6 ; cd qt5
          perl init-repository -f --module-subset=qt5compat,qt3d,qtbase,qtcharts,qtdeclarative,qtimageformats,qtquicktimeline,qtquick3d,qtshadertools,qtsvg,qtmultimedia
          ./configure.bat -release -static -platform win32-msvc -prefix "C:\QtVC143Static" -confirm-license -nomake examples -nomake tests -schannel -qt-zlib -qt-libjpeg -qt-libpng -qt-freetype -qt-pcre -qt-harfbuzz -qt-sqlite -no-sql-psql -no-sql-mysql -qt-tiff -qt-webp
          cmake --build . --parallel 4
          cmake --install .
      - name: Package binaries
        run: |
          7z a qt6.6_vc143_static.7z C:\QtVC143Static
      - name: Update Static Qt 6.5 MSVC Release
        uses: softprops/action-gh-release@v1
        with:
          tag_name: qt-static
          files: |
            qt6.6_vc143_static.7z