name: 'Qt Mingw64 Static'

on:
  push:
    branches:
      - win32-clang-msvc
jobs:
  win32-clang-msvc:
    name: Qt LLVM Static
    runs-on: windows-2019
    env:
      INSTALL_PREFIX: 'C:\QtStaticLLVM'
      OS: "win32-clang-msvc"
      QT_VERSION: "v6.4.0"
    steps:
      - name: Install LLVM and Clang
        uses: KyleMayes/install-llvm-action@v1
        with:
          version: "15.0.3"
      - name: Build script
        run: |
          clang -v
          cd C:/
          git clone https://code.qt.io/qt/qt5.git -b 6.4.0
          cd qt5
          perl init-repository -f --module-subset=default
          ./configure.bat -release -static -static-runtime -platform win32-clang-msvc -prefix "C:\QtStaticLLVM" -confirm-license -nomake examples -nomake tests
          cmake --build . --parallel 4
          cmake --install .
      - uses: actions/upload-artifact@v3
        with:
          name: qt6_mingw_static.zip
          path: C:\QtStaticLLVM
