name: 'Qt Mingw64 Static'

on:
  push:
    branches:
      - mingw64-dyn-ffmpeg-back
jobs:
  dyn-mingw64-mini-for-gui:
    name: Qt Mingw64 Static
    runs-on: windows-2019
    env:
      INSTALL_PREFIX: 'C:\QtStaticMingw64'
      OS: "win32-g++"
      QT_VERSION: "v6.4.0"
    steps:
      - name: Set Mingw64 Ninja
        run: |
          (new-object System.Net.WebClient).DownloadFile('https://github.com/cristianadam/mingw-builds/releases/download/v11.2.0-rev3/x86_64-11.2.0-release-posix-seh-rt_v9-rev3.7z','mingw64.7z')
          7z x -aoa -oC:\ mingw64.7z
          del mingw64.7z
          (new-object System.Net.WebClient).DownloadFile('https://github.com/ninja-build/ninja/releases/download/v1.11.1/ninja-win.zip','ninja-win.zip')
          7z x -aoa -oC:\ninja ninja-win.zip
          del ninja-win.zip
          (new-object System.Net.WebClient).DownloadFile('https://github.com/BtbN/FFmpeg-Builds/releases/download/latest/ffmpeg-master-latest-win64-gpl-shared.zip','ffmpeg-master-latest-win64-gpl-shared.zip')
          7z x -aoa -oC:\ffmpeg ffmpeg-master-latest-win64-gpl-shared.zip
          del ffmpeg-master-latest-win64-gpl-shared.zip
      # - uses: ilammy/msvc-dev-cmd@v1
      #   with:
      #     arch: amd64
      #     toolset: 14.2
      - name: Build script
        run: |
          $env:Path = "C:\mingw64\bin;C:\ninja;C:\ffmpeg\include;C:\ffmpeg\lib;C:\ffmpeg\bin;$env:Path"
          $env:QT_MEDIA_BACKEND = "ffmpeg"
          $env:FFMPEG_INCLUDE_DIRS = "C:\ffmpeg\include"
          $env:FFMPEG_LIBRARY_DIRS = "C:\ffmpeg\lib"
          cd C:/
          git clone https://code.qt.io/qt/qt5.git -b 6.4
          cd qt5
          perl init-repository -f --module-subset=qt5compat,qt3d,qtactiveqt,qtbase,qtcharts,qtdeclarative,qtimageformats,qtmultimedia,qtquicktimeline,qtquick3d,qtshadertools,qtsvg,qttools,qttranslations,qtlottie,qtvirtualkeyboard
          ./configure.bat -release -shared -platform win32-g++ -prefix "C:\QtStaticMingw64" -confirm-license -nomake examples -nomake tests
          cmake --build . --parallel 4
          cmake --install .
      - name: Package Directories
        run: |
          7z a qt6_dyn.7z C:\QtStaticMingw64
      - uses: actions/upload-artifact@v3
        with:
          name: qt6_mingw64-dyn-ffmpeg-back
          path: qt6_dyn.7z
