name: 'Windows 64-bit MSVC'

on:
  push:
    branches:
      - main
jobs:
  win64-msvc:
    name: Windows 64-bit MSVC QtBase
    runs-on: windows-2019
    env:
      INSTALL_PREFIX: 'C:\QtStatic'
      OS: "win64-msvc"
      QT_VERSION: "v6.4.0"
    steps:
      - name: Git Clone
        run: |
          git clone --depth=1 https://github.com/spatial-model-editor/sme_deps_qt.git q
      - name: Build script
        run: |
          cd q
          ./build.ps1
      - uses: actions/upload-artifact@v3
        with:
          path: ./artefacts/*
  # build:
  #   runs-on: windows-2019
  #   steps:
  #     - name: Cache static package
  #       id: install-cache
  #       uses: actions/cache@v3
  #       with:
  #         path: C:/vcpkg/installed/x64-mingw-static
  #         key: x64-mingw-static
  #     - name: build
  #       shell: cmd
  #       run: |
  #         vcpkg install qt[default-features]:x64-windows-static
  #         vcpkg export qt[default-features]:x64-windows-static --7zip --output-dir=./
  #     - uses: actions/upload-artifact@v3
  #       with:
  #         name: vcpkg-export
  #         path: ./vcpkg-export-*.7z
