name: 'Msvc Static'

on:
  push:
    branches:
      - msvc

jobs:
  win32-msvc:
    name: Qt MSVC Static Small For Gui MT
    runs-on: windows-2019
    steps:
      - name: Build script
        run: |
         # Clone Qt6 repo
          cd C:/
          git clone https://code.qt.io/qt/qt5.git -b 6.4.0
          cd qt5
          perl init-repository -f --module-subset=qt5compat,qt3d,qtactiveqt,qtbase,qtcharts,qtdatavis3d,qtdeclarative,qtimageformats,qtmultimedia,qtpositioning,qtlocation,qtquick3d,qtquicktimeline,qtshadertools,qtsvg,qtwebsockets,qttools,qttranslations,qtlottie,qtvirtualkeyboard
          # Create shadow build folder
          cd ..
          mkdir qt6_shadow
          cd qt6_shadow
          # Setup the compiler
          cmd.exe /c "call `"C:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise\VC\Auxiliary\Build\vcvars64.bat`" && set > %temp%\vcvars.txt"
          Get-Content "$env:temp\vcvars.txt" | Foreach-Object { if ($_ -match "^(.*?)=(.*)$") { Set-Content "env:\$($matches[1])" $matches[2] } }
          # Configure Qt5
          ..\qt5\configure.bat -release -static -static-runtime -platform win32-clang-msvc -prefix "C:\QtStaticMSVC" -confirm-license -nomake examples -nomake tests
          cmake --build . --parallel 4
          cmake --install .
      - name: Package binaries
        run: |
          7z a qt6_static.7z C:\QtStaticMSVC
      - uses: actions/upload-artifact@v3
        with:
          name: qt6_msvc_static_small_for_gui_MT
          path: qt6_static.7z
#MD编译
  win32-msvc-md:
    name: Qt LLVM Static Small For Gui MD
    runs-on: windows-2019
    steps:
      - name: Build script
        run: |
         # Clone Qt6 repo
          cd C:/
          git clone https://code.qt.io/qt/qt5.git -b 6.4.0
          cd qt5
          perl init-repository -f --module-subset=qt5compat,qt3d,qtactiveqt,qtbase,qtcharts,qtdatavis3d,qtdeclarative,qtimageformats,qtmultimedia,qtpositioning,qtlocation,qtquick3d,qtquicktimeline,qtshadertools,qtsvg,qtwebsockets,qttools,qttranslations,qtlottie,qtvirtualkeyboard
          # Create shadow build folder
          cd ..
          mkdir qt6_shadow
          cd qt6_shadow
          # Setup the compiler
          cmd.exe /c "call `"C:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise\VC\Auxiliary\Build\vcvars64.bat`" && set > %temp%\vcvars.txt"
          Get-Content "$env:temp\vcvars.txt" | Foreach-Object { if ($_ -match "^(.*?)=(.*)$") { Set-Content "env:\$($matches[1])" $matches[2] } }
          # Configure Qt5
          ..\qt5\configure.bat -release -static -platform win32-clang-msvc -prefix "C:\QtStaticMSVC" -confirm-license -nomake examples -nomake tests
          cmake --build . --parallel 4
          cmake --install .
      - name: Package binaries
        run: |
          7z a qt6_static.7z C:\QtStaticMSVC
      - uses: actions/upload-artifact@v3
        with:
          name: qt6_msvc_static_small_for_gui_MD
          path: qt6_static.7z